name: build-and-push
on:
  push:
	branches: [ "main" ]

jobs:
  docker:
	runs-on: ubuntu-22.04
	steps:
	  - uses: actions/checkout@v4

	  - uses: docker/setup-qemu-action@v3
	  - uses: docker/setup-buildx-action@v3

	  - name: Login to Gitea Registry
		uses: docker/login-action@v3
		with:
		  registry: tig.unfr.pw
		  username: ${{ gitea.actor }}
		  password: ${{ secrets.GITEAPAT }}   # PAT Gitea avec droits "packages:write"

	  - name: Build & Push
		uses: docker/build-push-action@v6
		with:
		  context: .
		  file: Dockerfile
		  platforms: linux/amd64,linux/arm64
		  push: true
		  tags: |
			tig.unfr.pw/${{ gitea.repository_owner }}/trakt:latest
			tig.unfr.pw/${{ gitea.repository_owner }}/trakt:${{ gitea.sha }}
