name: Build and push to Docker Hub
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: |
            docker.io/diabolino/trakt_enhanced:latest
            docker.io/diabolino/trakt_enhanced:${{ github.sha }}
